### ISSUE TITLE
Script sometimes doesn't register when mouse button is released

### ISSUE THREAD

**Issue by Hvalfisk** [IronSavior/wheeler.ahk#1]
When moving the cursor very fast at the same time as holding down the button, and very quickly after releasing the button again, the HotKey Button Up will not trigger, and GetKeyState will also continue to report the button as being held down.  
Script will keep scrolling until mouse button is clicked again. 

To reproduce it, move cursor up and down very fast, and hold down the mouse button on every downwards movement.  
I actually do this a lot in real use. It's when scrolling long pages. 

Commenting out the scroll wheel clicks stops it from happening. 
So it seems to be the sending of multiple clicks that interferes with AutoHotkey's ability to receive the Button Up event. 

Setting `SetMouseDelay, -1` did seem to help with this quite a lot. And I think `SetBatchLines, -1` also helped. 

Please help 🙏

**Comment by Hvalfisk** [comment]
My recent changes have actually made the bug appear so seldomly that it is not a problem anymore. I really need to make an effort to reproduce it now. 

Now if only we could port/copy this functionality over to GNU/Linux somehow. One can dream.

**Comment by IronSavior** [comment]
Would you like to submit a PR for your change?

**Comment by Hvalfisk** [comment]
I think some of the changes I have made might be of use. 

But my version has right mouse button hardcoded, it does both X and Y axis, it does multiple scroll-wheel ticks each loop, and it has a threshold for how far you need to move the cursor away from the starting point before scrolling starts happening. 

I'm not actually sure how many of these changes I made and how much of it was in the original script. I have been using and modifying it since 2013. 

I'm also not sure about what to do with the license and comment at the top of the code. The description doesn't fit my version as well, but I do think your name should stay. 

I can make a PR and maybe it will be interesting.

**Comment by Hvalfisk** [comment]
I just came up with a great idea, it should only scroll one axis at a time

**Comment by Hvalfisk** [comment]
By the way, what does the `esmb_` variable prefix mean?

**Comment by IronSavior** [comment]
> By the way, what does the `esmb_` variable prefix mean?

IIRC, something like "emulate scrolling middle button"

**Comment by IronSavior** [comment]
I see the PR #3.  Thanks, I'll check it out.

**Comment by IronSavior** [comment]
Thanks for the pull request! I merged your PR and followed up with another change to make it more configurable and easier to read. When I did that, I also changed some of the defaults away from what your script contained, so be sure to edit the configuration if you want to change up the buttons or thresholds.
